In [72]:

import ajcs
from  copy import deepcopy

In [60]:
import numpy as np
import scipy.sparse as sp

In [85]:
nx = 3
nt = 3
Qs = [sp.random(nx,nx, 1) for i in range(nt)]
dts = np.array([1 for i in range(nt)])



IndexError: index 1 is out of bounds for axis 1 with size 1

In [88]:
ajcs.AJCS(Qs, dts)


IndexError: index 1 is out of bounds for axis 1 with size 1

In [ ]:
%debug

In [89]:
ajcs.qtilde(Qs)

([matrix([[0.        , 0.23561915, 0.76438085],
          [0.47296238, 0.        , 0.52703762],
          [0.6028555 , 0.3971445 , 0.        ]]),
  matrix([[0.        , 0.53113008, 0.46886992],
          [0.68433785, 0.        , 0.31566215],
          [0.49911618, 0.50088382, 0.        ]]),
  matrix([[0.        , 0.65984376, 0.34015624],
          [0.4249919 , 0.        , 0.5750081 ],
          [0.99600921, 0.00399079, 0.        ]])],
 array([[1.03864171, 1.19617502, 0.48316944],
        [1.44921148, 0.86585462, 0.94553971],
        [1.06375995, 1.33169715, 0.97330835]]))